services:
  - type: web
    name: r3d-telegram-bot
    runtime: python
    buildCommand: bash build.sh
    startCommand: python3 main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SIGHTENGINE_API_USER
        sync: false
      - key: SIGHTENGINE_API_SECRET
        sync: false
    autoDeploy: true
